/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef AGENTXIOT_H
#define AGENTXIOT_H

/* function declarations */
void init_agentxIOT(void);
Netsnmp_Node_Handler handle_ROString;
Netsnmp_Node_Handler handle_ROInteger;

#endif /* AGENTXIOT_H */
