/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "agentxIOT.h"

extern char ROStringVar[80];
extern int  ROIntegerVar;

/** Initializes the agentxIOT module */
void
init_agentxIOT(void)
{
    const oid ROString_oid[] = { 1,3,6,1,3,9999,1,1 };
    const oid ROInteger_oid[] = { 1,3,6,1,3,9999,1,2 };

  DEBUGMSGTL(("agentxIOT", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ROString", handle_ROString,
                               ROString_oid, OID_LENGTH(ROString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ROInteger", handle_ROInteger,
                               ROInteger_oid, OID_LENGTH(ROInteger_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_ROString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &ROStringVar/* XXX: a pointer to the scalar's data */,
                                     sizeof(ROStringVar)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ROString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_ROInteger(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &ROIntegerVar/* XXX: a pointer to the scalar's data */,
                                     sizeof(ROIntegerVar)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ROInteger\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
