/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef IOTUSERTABLE_INTERFACE_H
#define IOTUSERTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "iotUserTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _iotUserTable_initialize_interface(iotUserTable_registration * user_ctx,
                                    u_long flags);
void _iotUserTable_shutdown_interface(iotUserTable_registration * user_ctx);

iotUserTable_registration *
iotUserTable_registration_get( void );

iotUserTable_registration *
iotUserTable_registration_set( iotUserTable_registration * newreg );

netsnmp_container *iotUserTable_container_get( void );
int iotUserTable_container_size( void );

    iotUserTable_rowreq_ctx * iotUserTable_allocate_rowreq_ctx(void *);
void iotUserTable_release_rowreq_ctx(iotUserTable_rowreq_ctx *rowreq_ctx);

int iotUserTable_index_to_oid(netsnmp_index *oid_idx,
                            iotUserTable_mib_index *mib_idx);
int iotUserTable_index_from_oid(netsnmp_index *oid_idx,
                              iotUserTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void iotUserTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* IOTUSERTABLE_INTERFACE_H */
/** @} */
