/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef IOTUSERTABLE_OIDS_H
#define IOTUSERTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table iotUserTable */
#define IOTUSERTABLE_OID              1,3,6,1,3,9999,2,1


#define COLUMN_ROSTRINGCOL1         1
    
#define COLUMN_ROINTCOL2         2
    

#define IOTUSERTABLE_MIN_COL   COLUMN_ROSTRINGCOL1
#define IOTUSERTABLE_MAX_COL   COLUMN_ROINTCOL2
    


#ifdef __cplusplus
}
#endif

#endif /* IOTUSERTABLE_OIDS_H */
