/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for iotUserTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "iotUserTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "iotUserTable_interface.h"

const oid iotUserTable_oid[] = { IOTUSERTABLE_OID };
const int iotUserTable_oid_size = OID_LENGTH(iotUserTable_oid);

    iotUserTable_registration  iotUserTable_user_context;

void initialize_table_iotUserTable(void);
void shutdown_table_iotUserTable(void);


/**
 * Initializes the iotUserTable module
 */
void
init_iotUserTable(void)
{
    DEBUGMSGTL(("verbose:iotUserTable:init_iotUserTable","called\n"));

    /*
     * TODO:300:o: Perform iotUserTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("iotUserTable"))
        initialize_table_iotUserTable();

} /* init_iotUserTable */

/**
 * Shut-down the iotUserTable module (agent is exiting)
 */
void
shutdown_iotUserTable(void)
{
    if (should_init("iotUserTable"))
        shutdown_table_iotUserTable();

}

/**
 * Initialize the table iotUserTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_iotUserTable(void)
{
    iotUserTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:iotUserTable:initialize_table_iotUserTable","called\n"));

    /*
     * TODO:301:o: Perform iotUserTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize iotUserTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("iotUserTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _iotUserTable_initialize_interface(user_context, flags);
} /* initialize_table_iotUserTable */

/**
 * Shutdown the table iotUserTable 
 */
void
shutdown_table_iotUserTable(void)
{
    /*
     * call interface shutdown code
     */
    _iotUserTable_shutdown_interface(&iotUserTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
iotUserTable_rowreq_ctx_init(iotUserTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra iotUserTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* iotUserTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void iotUserTable_rowreq_ctx_cleanup(iotUserTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra iotUserTable rowreq cleanup.
     */
} /* iotUserTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
iotUserTable_pre_request(iotUserTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform iotUserTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* iotUserTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
iotUserTable_post_request(iotUserTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform iotUserTable post-request actions.
     */

    return MFD_SUCCESS;
} /* iotUserTable_post_request */


/** @{ */
