/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "iotUserTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement iotUserTable get routines.
 * TODO:240:M: Implement iotUserTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table iotUserTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IOT-MIB::iotUserTable is subid 1 of Tables.
 * Its status is Current.
 * OID: .1.3.6.1.3.9999.2.1, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement iotUserTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param ROStringCol1_ptr
 * @param ROStringCol1_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
iotUserTable_indexes_set_tbl_idx(iotUserTable_mib_index *tbl_idx, char *ROStringCol1_val_ptr,  size_t ROStringCol1_val_ptr_len)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_indexes_set_tbl_idx","called\n"));

    /* ROStringCol1(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    tbl_idx->ROStringCol1_len = sizeof(tbl_idx->ROStringCol1)/sizeof(tbl_idx->ROStringCol1[0]); /* max length */
    /*
     * make sure there is enough space for ROStringCol1 data
     */
    if ((NULL == tbl_idx->ROStringCol1) ||
        (tbl_idx->ROStringCol1_len <
         (ROStringCol1_val_ptr_len))) {
        snmp_log(LOG_ERR,"not enough space for value (ROStringCol1_val_ptr)\n");
        return MFD_ERROR;
    }
    tbl_idx->ROStringCol1_len = ROStringCol1_val_ptr_len;
    memcpy( tbl_idx->ROStringCol1, ROStringCol1_val_ptr, ROStringCol1_val_ptr_len* sizeof(ROStringCol1_val_ptr[0]) );
    

    return MFD_SUCCESS;
} /* iotUserTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
iotUserTable_indexes_set(iotUserTable_rowreq_ctx *rowreq_ctx, char *ROStringCol1_val_ptr,  size_t ROStringCol1_val_ptr_len)
{
    DEBUGMSGTL(("verbose:iotUserTable:iotUserTable_indexes_set","called\n"));

    if(MFD_SUCCESS != iotUserTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , ROStringCol1_val_ptr, ROStringCol1_val_ptr_len
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != iotUserTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* iotUserTable_indexes_set */


/*---------------------------------------------------------------------
 * IOT-MIB::iotUserTableEntry.ROIntCol2
 * ROIntCol2 is subid 2 of iotUserTableEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.9999.2.1.1.2
 * Description:
Just a test integer for table
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the ROIntCol2 data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ROIntCol2_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ROIntCol2_get( iotUserTable_rowreq_ctx *rowreq_ctx, long * ROIntCol2_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ROIntCol2_val_ptr );


    DEBUGMSGTL(("verbose:iotUserTable:ROIntCol2_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ROIntCol2 data.
 * copy (* ROIntCol2_val_ptr ) from rowreq_ctx->data
 */
    (* ROIntCol2_val_ptr ) = rowreq_ctx->data.ROIntCol2;

    return MFD_SUCCESS;
} /* ROIntCol2_get */



/** @} */
